advanced:
  algorithm_tuning:
    convergence_monitoring: true
    enable_adaptive_parameters: false
    parameter_learning_rate: 0.01
  experimental_features:
    enable_edge_computing: false
    enable_federated_learning: false
    enable_quantum_optimization: false
  integration:
    custom_objective_functions: []
    external_optimization_apis: []
    third_party_validators: []
constraints:
  max_handover_frequency: 10
  max_latency_ms: 50
  min_satellites_per_pool: 5
  min_signal_quality: -100.0
error_handling:
  error_logging_level: WARNING
  fallback_strategy: simplified_optimization
  max_retry_attempts: 3
  recovery_strategies:
    handover_optimization_failure: disable_handover
    multi_objective_failure: use_weighted_sum
    pool_planning_failure: use_single_pool
    rl_failure: fallback_to_traditional
  retry_delay_seconds: 1.0
handover_optimizer:
  algorithm: predictive_optimization
  fallback_strategies: 3
  network_impact_weight: 0.4
  prediction_horizon_minutes: 15
  risk_tolerance: 0.2
  thresholds:
    elevation_minimum_deg: 5.0
    elevation_optimal_deg: 15.0
    handover_preparation_time_sec: 30.0
    signal_degradation_db: -10.0
  trigger_sensitivity: medium
  user_impact_weight: 0.6
logging:
  enable_decision_trace: false
  enable_performance_logs: true
  enable_rl_debug: false
  log_file_rotation: true
  log_level: INFO
  max_log_file_size_mb: 100
multi_objective_optimizer:
  algorithm: nsga2
  convergence_tolerance: 1e-6
  crossover_rate: 0.9
  elitism_rate: 0.1
  max_generations: 50
  mutation_rate: 0.1
  objectives:
    maximize_coverage: true
    maximize_energy_efficiency: true
    maximize_signal_quality: true
    minimize_handover_cost: true
  population_size: 100
optimization_objectives:
  coverage_weight: 0.3
  energy_efficiency_weight: 0.1
  handover_cost_weight: 0.2
  signal_quality_weight: 0.4
output:
  compression_enabled: false
  format_version: v2.0
  include_debug_info: false
  include_intermediate_results: false
  include_performance_metrics: true
  include_rl_decisions: true
  precision_digits: 6
  remove_null_fields: true
performance_monitoring:
  benchmark_targets:
    constraint_satisfaction_min_rate: 0.95
    decision_quality_min_score: 0.8
    memory_usage_max_mb: 300
    processing_time_max_seconds: 10.0
  enable_detailed_metrics: true
  optimization_settings:
    adaptive_algorithm_selection: false
    cache_intermediate_results: true
    early_termination_enabled: true
    parallel_processing: true
pool_planner:
  algorithm: dynamic_clustering
  coverage_overlap_threshold: 0.15
  diversity_factor: 0.3
  max_pool_size: 20
  max_pools: 3
  min_pool_size: 5
  signal_quality_threshold: -90.0
  stability_weight: 0.4
rl_extension:
  action_space_size: 64
  hybrid_mode: true
  rl_agent:
    agent_type: dqn
    batch_size: 32
    epsilon_decay: 0.995
    epsilon_end: 0.01
    epsilon_start: 1.0
    learning_rate: 0.001
    memory_size: 10000
    update_frequency: 4
  rl_confidence_threshold: 0.7
  rl_enabled: false
  rl_environment:
    action_space_size: 64
    reward_weights:
      coverage: 0.3
      energy_efficiency: 0.1
      handover_cost: -0.2
      signal_quality: 0.4
    state_dimensions: 128
  state_dimensions: 128
validation:
  enable_constraint_checking: true
  enable_input_validation: true
  enable_output_validation: true
  enable_performance_benchmarking: false
  test_scenarios:
  - expected_processing_time_max: 8.0
    name: high_satellite_density
    satellite_count: 1000
  - expected_pools_min: 1
    min_signal_strength: -110.0
    name: low_signal_quality
  - expected_strategies_min: 3
    handover_frequency: 15
    name: frequent_handovers
