# Handover-RL 數據配置

# orbit-engine 數據源
orbit_engine:
  root: "/home/sat/satellite/orbit-engine"

  # Stage 6 輸出（3GPP 事件）
  stage6:
    path: "/home/sat/satellite/orbit-engine/data/outputs/stage6"
    pattern: "stage6_research_*.json"

  # Stage 5 輸出（信號品質）
  stage5:
    path: "/home/sat/satellite/orbit-engine/data/outputs/stage5"
    pattern: "stage5_signal_*.json"

# 訓練數據分割
data_split:
  train_ratio: 0.75      # 75% 訓練
  val_ratio: 0.125       # 12.5% 驗證
  test_ratio: 0.125      # 12.5% 測試
  random_seed: 42        # 隨機種子（保證可重現）

# 3GPP 事件過濾
event_filter:
  use_a3: true          # 使用 A3 事件
  use_a4: true          # 使用 A4 事件
  use_a5: true          # 使用 A5 事件
  use_d2: true          # 使用 D2 事件
  min_rsrp: -150.0      # RSRP 最小值過濾
  max_rsrp: -20.0       # RSRP 最大值過濾

# 本地數據緩存
cache:
  enable: true
  path: "data/cache"
