# 3GPP NTN 標準參數配置文件
# 3GPP NTN Standards Configuration File
# 學術級 Grade B 標準配置

metadata:
  standard_organization: "3GPP"
  specifications:
    - "3GPP TS 38.821 v17.0.0"  # NTN Solutions for 5G
    - "3GPP TS 36.331 v17.1.0"  # RRC Protocol
    - "3GPP TS 38.213 v17.1.0"  # Physical layer procedures
  last_updated: "2024-12-01"
  grade: "B"
  compliance_status: "academic_verified"

# NTN系統參數
ntn_system_parameters:
  source: "3GPP TS 38.821"
  satellite_parameters:
    leo_altitude_range_km: [300, 1500]
    meo_altitude_range_km: [7000, 25000]
    geo_altitude_km: 35786

    max_coverage_distance_km: 3000
    min_elevation_angle_deg: 10
    handover_margin_db: 3

  timing_parameters:
    timing_advance_max_ms: 20.0
    round_trip_delay_max_ms: 25.4
    doppler_compensation: "enabled"
    frequency_offset_compensation_hz: 50000

# 測量事件標準
measurement_events:
  source: "3GPP TS 36.331 v17.1.0"

  # A3事件: 鄰區變得比服務小區好
  event_a3:
    description: "Neighbour becomes amount of offset better than PCell"
    hysteresis_db: 3.0
    time_to_trigger_ms: 480
    offset_db: 3.0
    reportOnLeave: true

  # A4事件: 服務小區變得比門檻差
  event_a4:
    description: "Serving becomes worse than threshold"
    threshold_rsrp_dbm: -106
    hysteresis_db: 2.0
    time_to_trigger_ms: 160
    reportOnLeave: false

  # A5事件: 服務小區變得比門檻1差且鄰區變得比門檻2好
  event_a5:
    description: "PCell becomes worse than threshold1 and neighbour becomes better than threshold2"
    threshold1_rsrp_dbm: -110  # 服務小區門檻
    threshold2_rsrp_dbm: -100  # 鄰區門檻
    hysteresis_db: 2.0
    time_to_trigger_ms: 320
    reportOnLeave: true

  # B1事件: 鄰區變得比門檻好
  event_b1:
    description: "Inter RAT neighbour becomes better than threshold"
    threshold_rsrp_dbm: -100
    hysteresis_db: 2.0
    time_to_trigger_ms: 640

  # B2事件: 服務小區變得比門檻1差且鄰區變得比門檻2好
  event_b2:
    description: "PCell becomes worse than threshold1 and inter RAT neighbour becomes better than threshold2"
    threshold1_rsrp_dbm: -105
    threshold2_rsrp_dbm: -95
    hysteresis_db: 3.0
    time_to_trigger_ms: 640

# NTN專用測量事件
ntn_specific_events:
  source: "3GPP TS 38.821"

  # D2事件: 距離變化事件
  event_d2:
    description: "Distance based handover event"
    distance_threshold_km: 1500
    min_distance_km: 1200
    hysteresis_km: 50
    time_to_trigger_ms: 320

  # 衛星可見性事件
  visibility_event:
    description: "Satellite visibility change"
    min_elevation_deg: 10
    elevation_hysteresis_deg: 2
    time_to_trigger_ms: 1000

  # 都卜勒頻移事件
  doppler_event:
    description: "Excessive Doppler shift"
    max_doppler_shift_hz: 40000
    doppler_hysteresis_hz: 5000
    time_to_trigger_ms: 500

# 換手參數
handover_parameters:
  source: "3GPP TS 36.331, 3GPP TS 38.821"

  handover_types:
    intra_satellite: "Same satellite beam change"
    inter_satellite: "Different satellite"
    satellite_to_terrestrial: "NTN to TN handover"
    terrestrial_to_satellite: "TN to NTN handover"

  handover_timing:
    preparation_time_ms: 50
    execution_time_ms: 150
    completion_time_ms: 100
    total_interruption_time_ms: 300

  handover_thresholds:
    rsrp_hysteresis_db: 3.0
    rsrq_hysteresis_db: 2.0
    sinr_hysteresis_db: 2.0

# 物理層參數
physical_layer:
  source: "3GPP TS 38.213"

  frequency_bands:
    n256: # 26.5-29.5 GHz
      frequency_range_ghz: [26.5, 29.5]
      duplex_mode: "TDD"
      channel_bandwidth_mhz: [50, 100, 200, 400]

    n257: # 28 GHz
      frequency_range_ghz: [26.5, 29.5]
      duplex_mode: "TDD"
      channel_bandwidth_mhz: [50, 100, 200, 400]

    n258: # 26 GHz
      frequency_range_ghz: [24.25, 27.5]
      duplex_mode: "TDD"
      channel_bandwidth_mhz: [50, 100, 200, 400]

  power_control:
    max_eirp_dbm: 40
    power_control_step_db: 1
    power_headroom_db: 3

# 服務品質參數
qos_parameters:
  source: "3GPP TS 23.501"

  service_types:
    embb: # Enhanced Mobile Broadband
      latency_target_ms: 4
      throughput_target_mbps: 100
      reliability_target: 0.99

    urllc: # Ultra-Reliable Low Latency Communications
      latency_target_ms: 1
      throughput_target_mbps: 10
      reliability_target: 0.99999

    mmtc: # Massive Machine Type Communications
      latency_target_ms: 10000
      throughput_target_kbps: 1
      reliability_target: 0.9

  signal_quality_requirements:
    voice_call:
      min_rsrp_dbm: -105
      min_sinr_db: 0

    video_call:
      min_rsrp_dbm: -100
      min_sinr_db: 5

    data_service:
      min_rsrp_dbm: -110
      min_sinr_db: -3

# RRC協議參數
rrc_parameters:
  source: "3GPP TS 36.331"

  cell_reselection:
    s_non_intra_search_db: 31
    thresh_serving_low_db: 7
    cell_reselection_priority: 6
    s_intra_search_db: 62

  measurement_configuration:
    measurement_gaps_ms: 6
    measurement_period_ms: 200
    filter_coefficient: 4
    max_report_cells: 8

  mobility_control:
    t310_ms: 1000  # RLF timer
    t311_ms: 10000 # RLF timer
    n310: 1        # Consecutive "out-of-sync" indications
    n311: 1        # Consecutive "in-sync" indications