# ITU-R 標準參數配置文件
# ITU-R Standards Configuration File
# 學術級 Grade B 標準配置

metadata:
  standard_organization: "ITU-R"
  last_updated: "2024-12-01"
  grade: "B"
  compliance_status: "academic_verified"

# ITU-R P.618 衛星鏈路預算標準
satellite_link_budget:
  source: "ITU-R P.618-13"
  atmospheric_attenuation:
    clear_sky_loss_db_per_km: 0.05
    rain_attenuation_model: "ITU-R P.838"
    cloud_attenuation_model: "ITU-R P.840"
    scintillation_model: "ITU-R P.618"

  elevation_thresholds:
    minimum_operational: 5.0    # 度
    standard_operational: 10.0  # 度
    optimal_operational: 15.0   # 度
    high_precision: 25.0        # 度

  path_loss_formula: "32.45 + 20*log10(f_ghz) + 20*log10(d_km)"
  free_space_loss_coefficient: 32.45

# ITU-R P.1411 地面傳播模型
terrestrial_propagation:
  source: "ITU-R P.1411-10"
  signal_quality_thresholds:
    excellent:
      rsrp_min_dbm: -80
      ber_max: "1e-6"
      application: "高清視頻、實時通訊"

    good:
      rsrp_min_dbm: -90
      ber_max: "1e-5"
      application: "標清視頻、語音通話"

    fair:
      rsrp_min_dbm: -100
      ber_max: "1e-4"
      application: "語音通話、數據傳輸"

    poor:
      rsrp_min_dbm: -110
      ber_max: "1e-3"
      application: "低速數據、文字通訊"

# ITU-R P.837 降雨模型
rain_model:
  source: "ITU-R P.837-7"
  rain_rate_coefficients:
    # 頻率相關係數 (簡化表示)
    ku_band_12ghz:
      k_horizontal: 0.0188
      k_vertical: 0.0168
      alpha_horizontal: 1.217
      alpha_vertical: 1.200

    ka_band_20ghz:
      k_horizontal: 0.0751
      k_vertical: 0.0691
      alpha_horizontal: 1.099
      alpha_vertical: 1.065

# ITU-R推薦LEO衛星參數
leo_satellite_parameters:
  source: "ITU-R Recommendations"
  default_parameters:
    altitude_range_km: [200, 2000]
    typical_altitude_km: 600
    orbital_period_minutes: 96
    inclination_range_deg: [0, 90]
    typical_inclination_deg: 55
    frequency_bands:
      ku_band_ghz: [10.7, 14.5]
      ka_band_ghz: [17.7, 31.0]

  link_parameters:
    typical_eirp_dbw: 36.0
    typical_antenna_gain_dbi: 40.0
    noise_figure_db: 3.0
    path_loss_margin_db: 3.0

# 環境調整係數
environmental_factors:
  source: "ITU-R P.618"
  terrain_factors:
    open_area: 1.0
    urban_environment: 1.1
    mountainous_terrain: 1.2
    dense_urban: 1.3

  weather_factors:
    clear_sky: 1.0
    light_rain: 1.1
    moderate_rain: 1.2
    heavy_rain: 1.4
    storm_conditions: 1.6

# 頻率分配標準
frequency_allocation:
  source: "ITU-R Radio Regulations"
  satellite_services:
    fixed_satellite_service:
      ku_band_downlink: [10.7, 12.75]  # GHz
      ku_band_uplink: [14.0, 14.5]     # GHz
      ka_band_downlink: [17.7, 21.2]   # GHz
      ka_band_uplink: [27.5, 31.0]     # GHz

    mobile_satellite_service:
      s_band: [1.525, 1.660]          # GHz
      l_band: [1.525, 1.559]          # GHz

# 測量精度標準
measurement_standards:
  source: "ITU-R F.1330"
  rsrp_measurement:
    accuracy_db: 3.0
    measurement_period_ms: 200
    averaging_samples: 16

  coordinate_accuracy:
    latitude_precision_deg: 0.0001
    longitude_precision_deg: 0.0001
    altitude_precision_m: 10.0

  timing_accuracy:
    synchronization_precision_us: 1.0
    measurement_interval_s: 0.1