# 衛星星座配置 - Grade A學術標準 (基於官方技術文件)
# 消除硬編碼值，實現配置驅動的參數管理

# 星座基本信息
constellations:
  starlink:
    name: "Starlink"
    operator: "SpaceX"
    orbit_type: "LEO"
    altitude_km: 550
    altitude_range_km: [500, 600]  # 允許的高度範圍
    inclination_deg: 53.0
    total_satellites: 4000

    # 信號參數 (基於FCC文件和公開技術規格)
    signal_parameters:
      frequency_hz: 2.1e9  # Band n1 (2110-2170 MHz)
      bandwidth_hz: 20e6   # 20 MHz
      eirp_dbm: 50.0      # dBm (典型值，基於FCC文件)
      eirp_range_dbm: [45.0, 55.0]  # 允許範圍

    # 鏈路預算參數
    link_budget:
      antenna_gain_dbi: 35.0      # 衛星天線增益
      feeder_loss_db: 1.5         # 饋線損耗
      pointing_loss_db: 0.5       # 指向損耗
      polarization_loss_db: 0.3   # 極化損耗

  oneweb:
    name: "OneWeb"
    operator: "OneWeb"
    orbit_type: "LEO"
    altitude_km: 1200
    altitude_range_km: [1100, 1300]
    inclination_deg: 87.4
    total_satellites: 648

    # 信號參數 (基於官方技術文件)
    signal_parameters:
      frequency_hz: 2.1e9
      bandwidth_hz: 20e6
      eirp_dbm: 55.0      # dBm (較高軌道，較高EIRP)
      eirp_range_dbm: [50.0, 60.0]

    # 鏈路預算參數
    link_budget:
      antenna_gain_dbi: 38.0      # 較高增益補償距離
      feeder_loss_db: 1.8
      pointing_loss_db: 0.6
      polarization_loss_db: 0.3

  kuiper:
    name: "Project Kuiper"
    operator: "Amazon"
    orbit_type: "LEO"
    altitude_km: 630
    altitude_range_km: [590, 670]
    inclination_deg: 51.9
    total_satellites: 3236

    # 信號參數 (基於FCC申請文件)
    signal_parameters:
      frequency_hz: 2.0e9
      bandwidth_hz: 20e6
      eirp_dbm: 48.0      # dBm (中等軌道高度)
      eirp_range_dbm: [43.0, 53.0]

    # 鏈路預算參數
    link_budget:
      antenna_gain_dbi: 36.0      # 中等增益
      feeder_loss_db: 1.6
      pointing_loss_db: 0.5
      polarization_loss_db: 0.3

# 地面終端配置 (基於3GPP NTN標準)
ground_terminal:
  # 用戶設備 (UE) 天線參數
  ue_antenna:
    gain_dbi: 2.15            # 典型偶極天線增益
    gain_range_dbi: [0, 5]    # 允許範圍
    noise_figure_db: 7.0      # 典型UE噪聲指數
    cable_loss_db: 2.0        # 電纜損耗

  # 環境參數
  environment:
    temperature_k: 290        # 標準環境溫度
    atmospheric_loss_db: 0.5  # 大氣損耗 (L波段)

# 3GPP NTN標準參數 (TS 38.331, TR 38.821)
gpp_ntn_parameters:
  # 測量事件門檻 (Section 5.5.4)
  measurement_events:
    a4_threshold_range_dbm: [-156, -30]    # A4事件門檻範圍
    a5_threshold_range_dbm: [-156, -30]    # A5事件門檻範圍

  # 測量偏移參數 (Section 6.3.5)
  measurement_offsets:
    frequency_offset_range_db: [-15, 15]   # Ofn範圍
    cell_offset_range_db: [-24, 24]        # Ocn範圍

  # NTN特定參數
  ntn_specific:
    max_propagation_delay_ms: 25.77        # 最大傳播延遲 (GEO)
    leo_propagation_delay_ms: 2.7          # LEO典型延遲
    timing_advance_range_us: [0, 20000]    # 時間提前量範圍

# 信號質量評估標準 (基於3GPP TS 36.214)
signal_quality_standards:
  rsrp_thresholds:
    excellent: -70        # 優秀
    good: -80            # 良好
    fair: -90            # 一般
    poor: -100           # 差
    very_poor: -110      # 很差
    minimum: -120        # 最低可用

  rsrq_thresholds:
    excellent: -8         # 優秀
    good: -12            # 良好
    fair: -15            # 一般
    poor: -18            # 差
    minimum: -25         # 最低可用

  sinr_thresholds:
    excellent: 20         # 優秀
    good: 13             # 良好
    fair: 7              # 一般
    poor: 3              # 差
    very_poor: 0         # 很差
    minimum: -10         # 最低可用

  # 質量評估權重配置 (基於3GPP重要性)
  assessment_weights:
    rsrp_weight: 0.4      # RSRP權重 40% (覆蓋能力)
    rsrq_weight: 0.3      # RSRQ權重 30% (質量指標)
    sinr_weight: 0.3      # SINR權重 30% (性能指標)

  # 整體質量等級門檻
  quality_grades:
    excellent_threshold: 85   # 優秀門檻
    good_threshold: 70       # 良好門檻
    fair_threshold: 50       # 一般門檻
    poor_threshold: 30       # 差門檻
    # 低於30為UNUSABLE

# 物理約束驗證參數
physical_constraints:
  leo_orbit:
    altitude_range_km: [400, 1500]        # LEO軌道高度範圍
    velocity_range_kms: [7.0, 8.5]        # 軌道速度範圍

  elevation_angle:
    minimum_deg: 0                         # 最小仰角
    maximum_deg: 90                        # 最大仰角
    service_threshold_deg: 10              # 服務門檻

  path_loss:
    frequency_ghz: 2.1                     # 工作頻率
    tolerance_db: 5.0                      # 允許誤差

  # NTN干擾模型 (基於ITU-R M.2292)
  ntn_interference:
    interference_to_noise_db: 3.0          # 干擾與噪聲功率比 (I/N = 3dB, ITU-R M.2292標準)

# 驗證門檻 (Grade A學術標準)
validation_thresholds:
  signal_accuracy_rate: 0.90              # 信號計算準確率要求
  physics_compliance_rate: 0.95           # 物理約束合規率要求
  gpp_compliance_rate: 1.00               # 3GPP標準合規率要求
  time_sync_accuracy: 0.95                # 時間同步精度要求